### ISSUE TITLE
Are these useful?

### ISSUE THREAD

**Issue by tcsenpai** [goodix-fp-linux-dev/goodix-firmware#4]
Before going straight PR, I just made a repo (and then I found this one) for a couple of Goodix devices.

[https://github.com/tcsenpai/goodix-debian-linux-drivers-fingerprint-by-dell](https://github.com/tcsenpai/goodix-debian-linux-drivers-fingerprint-by-dell)

I don't know if you need these or not but they work for:

-     27c6:538c
-     27c6:533c
-     27c6:530c
-     27c6:5840
-     27c6:550a

Feel free to reupload or do whatever you guys want

**Comment by TheWeirdDev** [comment]
Thanks, but closed source drivers are not so useful for the open source community.
